// Engineering Entrepreneurship Programming — content model
// ---------------------------------------------------------------------------
// The site's wording lives in editable Markdown files in src/content/. This
// module loads those files, parses the YAML data block at the top of each, and
// exposes it to the app as typed values. To change any copy on the site, edit
// the Markdown in src/content/ and rebuild. Do not edit this file for wording.
// ---------------------------------------------------------------------------

import yaml from 'js-yaml';
import homeRaw from '../content/home.md?raw';
import pipelineRaw from '../content/pipeline.md?raw';
import programsRaw from '../content/programs.md?raw';
import productStudioRaw from '../content/product-studio.md?raw';
import founderRaw from '../content/founder.md?raw';
import advisorRaw from '../content/advisor.md?raw';
import mentorsRaw from '../content/mentors.md?raw';

/** Read the YAML data block (the part between the leading --- fences). */
function frontmatter(raw: string): Record<string, unknown> {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  return (m ? yaml.load(m[1]) : {}) as Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type Role = 'founder' | 'advisor';
export type StageId = 'explore' | 'validate' | 'build' | 'scale';
export type Accent = 'amber' | 'emerald' | 'garnet' | 'indigo';

export interface Brand {
  short: string;
  programName: string;
  faculty: string;
  centre: string;
}

export interface Landing {
  eyebrow: string;
  title: string;
  subtitle: string;
  roleQuestion: string;
  roleHint: string;
  intentTitle: string;
  intentBody: string;
  principlesTitle: string;
  pipelineTitle: string;
  pipelineSubtitle: string;
}

export interface RoleCard {
  role: Role;
  icon: string;
  title: string;
  body: string;
  cta: string;
}

export interface Principle {
  icon: string;
  title: string;
  body: string;
}

export interface Stat {
  value: string;
  label: string;
}

export interface Stage {
  id: StageId;
  order: number;
  accent: Accent;
  icon: string;
  name: string;
  tagline: string;
  purpose: string;
  entry: string;
  advance: string;
  owner: string;
}

export interface Program {
  id: string;
  stage: StageId;
  status: '' | 'new' | 'refreshed';
  name: string;
  kind: string;
  when: string;
  forWhom: string;
  summary: string;
  offers: string[];
  takeaway: string;
  flagship?: boolean;
}

export interface StudioFormat {
  icon: string;
  name: string;
  commitment: string;
  body: string;
}

export interface StudioPhase {
  n: number;
  icon: string;
  name: string;
  can: string;
  produces: string;
}

export interface ProductStudio {
  eyebrow: string;
  name: string;
  tagline: string;
  intro: string;
  forWhom: string;
  formatsTitle: string;
  formatsSubtitle: string;
  formats: StudioFormat[];
  phasesTitle: string;
  phasesSubtitle: string;
  phases: StudioPhase[];
  gateNote: string;
}

export interface Partner {
  name: string;
  category: string;
}

export interface FinderOption {
  label: string;
  stage: StageId;
}

export interface FinderQuestion {
  id: string;
  prompt: string;
  options: FinderOption[];
}

/** A simple titled step (used by the founder steps, flywheel, and recognition). */
export interface TextStep {
  title: string;
  body: string;
}

export interface Founder {
  eyebrow: string;
  title: string;
  intro: string;
  finderTitle: string;
  finderSubtitle: string;
  finderResultTitle: string;
  finderRestart: string;
  finderRecommended: string;
  pipelineTitle: string;
  pipelineSubtitle: string;
  readinessTitle: string;
  readinessBody: string;
  readinessA: string;
  readinessOr: string;
  readinessB: string;
  stepsTitle: string;
  steps: TextStep[];
}

export interface InvolvementWay {
  icon: string;
  title: string;
  body: string;
}

export interface Advisor {
  eyebrow: string;
  title: string;
  intro: string;
  flywheelTitle: string;
  flywheelSteps: TextStep[];
  waysTitle: string;
  ways: InvolvementWay[];
  peoTitle: string;
  peoBody: string;
  goalsTitle: string;
  goalsSubtitle: string;
  goals: Stat[];
  recognitionTitle: string;
  recognition: TextStep[];
  mentorsTitle: string;
  mentorsSubtitle: string;
  mentorsNote: string;
  ctaTitle: string;
  ctaBody: string;
  ctaButton: string;
}

export interface Mentor {
  name: string;
  role: string;
  field: string;
  bio: string;
  expertise: string[];
  quote: string;
}

export interface MentorsPage {
  eyebrow: string;
  title: string;
  subtitle: string;
  filterLabel: string;
  filterAll: string;
  countLabel: string;
  emptyLabel: string;
}

export interface Footer {
  blurb: string;
  rights: string;
  contact: string;
}

// ---------------------------------------------------------------------------
// Parsed content
// ---------------------------------------------------------------------------

const home = frontmatter(homeRaw);
export const brand = home.brand as Brand;
export const landing = home.landing as Landing;
export const heroStats = home.heroStats as Stat[];
export const principles = home.principles as Principle[];
export const roleCards = home.roleCards as RoleCard[];
export const footer = home.footer as Footer;

export const stages = frontmatter(pipelineRaw).stages as Stage[];
export const programs = frontmatter(programsRaw).programs as Program[];
export const productStudio = frontmatter(productStudioRaw)
  .productStudio as ProductStudio;

const founderFm = frontmatter(founderRaw);
export const founder = founderFm.founder as Founder;
export const finderQuestions = founderFm.finderQuestions as FinderQuestion[];

const advisorFm = frontmatter(advisorRaw);
export const advisor = advisorFm.advisor as Advisor;
export const partners = advisorFm.partners as Partner[];
export const mentorsPage = advisorFm.mentorsPage as MentorsPage;

export const mentors = frontmatter(mentorsRaw).mentors as Mentor[];
