// Engineering Entrepreneurship Programming — content model
// ---------------------------------------------------------------------------
// The site's wording lives in editable Markdown files in src/content/. This
// module loads those files, parses the YAML data block at the top of each, and
// exposes it to the app as typed values. To change any copy on the site, edit
// the Markdown in src/content/ and rebuild. Do not edit this file for wording.
// ---------------------------------------------------------------------------

import yaml from 'js-yaml';
import { getLang } from '../lib/lang';
import { UI } from './ui';

import homeEn from '../content/home.md?raw';
import homeFr from '../content/home.fr.md?raw';
import pipelineEn from '../content/pipeline.md?raw';
import pipelineFr from '../content/pipeline.fr.md?raw';
import programsEn from '../content/programs.md?raw';
import programsFr from '../content/programs.fr.md?raw';
import productStudioEn from '../content/product-studio.md?raw';
import productStudioFr from '../content/product-studio.fr.md?raw';
import makerLaunchEn from '../content/makerlaunch.md?raw';
import makerLaunchFr from '../content/makerlaunch.fr.md?raw';
import founderEn from '../content/founder.md?raw';
import founderFr from '../content/founder.fr.md?raw';
import advisorEn from '../content/advisor.md?raw';
import advisorFr from '../content/advisor.fr.md?raw';
import mentorsEn from '../content/mentors.md?raw';
import mentorsFr from '../content/mentors.fr.md?raw';
import launchpadEn from '../content/launchpad.md?raw';
import launchpadFr from '../content/launchpad.fr.md?raw';

// The site is bilingual; the language is fixed for the page load (switching
// reloads). Pick the matching Markdown and UI strings up front.
export const lang = getLang();
export const ui = UI[lang];

const pick = (en: string, fr: string) => (lang === 'fr' ? fr : en);
const homeRaw = pick(homeEn, homeFr);
const pipelineRaw = pick(pipelineEn, pipelineFr);
const programsRaw = pick(programsEn, programsFr);
const productStudioRaw = pick(productStudioEn, productStudioFr);
const makerLaunchRaw = pick(makerLaunchEn, makerLaunchFr);
const founderRaw = pick(founderEn, founderFr);
const advisorRaw = pick(advisorEn, advisorFr);
const mentorsRaw = pick(mentorsEn, mentorsFr);
const launchpadRaw = pick(launchpadEn, launchpadFr);

/** Read the YAML data block (the part between the leading --- fences). */
function frontmatter(raw: string): Record<string, unknown> {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  return (m ? yaml.load(m[1]) : {}) as Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type Role = 'founder' | 'advisor';
export type StageId = 'explore' | 'validate' | 'build' | 'scale';
export type Accent = 'amber' | 'emerald' | 'ember' | 'indigo';

export interface Brand {
  short: string;
  programName: string;
  faculty: string;
  centre: string;
}

export interface Landing {
  eyebrow: string;
  title: string;
  subtitle: string;
  roleQuestion: string;
  roleHint: string;
  principlesTitle: string;
  pipelineTitle: string;
  pipelineSubtitle: string;
  pipelineBranchLabel: string;
  heroImage?: string;
  heroImageAlt?: string;
}

export interface VenturesStrip {
  eyebrow: string;
  title: string;
  subtitle: string;
  note: string;
}

export interface RoleCard {
  role: Role;
  icon: string;
  title: string;
  body: string;
  cta: string;
}

export interface Principle {
  icon: string;
  title: string;
  body: string;
}

export interface Stat {
  value: string;
  label: string;
}

/** A photo in the homepage photo band (curated, editable stock URLs). */
export interface PhotoBandItem {
  src: string;
  alt: string;
  caption?: string;
}

export interface Stage {
  id: StageId;
  order: number;
  accent: Accent;
  icon: string;
  name: string;
  tagline: string;
  purpose: string;
  entry: string;
  advance: string;
  owner: string;
  /** Stages that belong to the MakerLaunch umbrella carry group: "makerlaunch". */
  group?: string;
}

/** The MakerLaunch umbrella that the Product Studio and Accelerator tracks sit under. */
export interface Umbrella {
  name: string;
  tagline: string;
}

/** A sub-track of the Explore stage (Courses or Extracurricular). */
export interface ExploreTrack {
  id: string;
  name: string;
  icon: string;
  tagline: string;
}

export interface Program {
  id: string;
  stage: StageId;
  status: '' | 'new' | 'refreshed';
  name: string;
  kind: string;
  when: string;
  forWhom: string;
  summary: string;
  offers: string[];
  takeaway: string;
  flagship?: boolean;
  /** For Explore-stage programs: which sub-track they belong to (courses | extracurricular). */
  track?: string;
}

export interface StudioPhase {
  n: number;
  icon: string;
  name: string;
  /** A one-line description of what this phase teaches. */
  can: string;
}

export interface ProductStudio {
  eyebrow: string;
  name: string;
  tagline: string;
  /** One line describing the cohort format (length, entry, funding). */
  formatNote: string;
  phases: StudioPhase[];
  gateNote: string;
  tools: string[];
  image?: string;
  imageAlt?: string;
}

/** One step of the MakerLaunch cohort journey. */
export interface MakerLaunchPhase {
  n: number;
  icon: string;
  name: string;
  /** A one-line description of what happens at this step. */
  focus: string;
}

/** One support the accelerator provides (funding, mentors, in-kind help...). */
export interface MakerLaunchSupport {
  icon: string;
  title: string;
  body: string;
}

export interface MakerLaunch {
  eyebrow: string;
  name: string;
  tagline: string;
  lead: string;
  journeyTitle: string;
  journeySubtitle: string;
  phases: MakerLaunchPhase[];
  supportsTitle: string;
  supportsSubtitle: string;
  supports: MakerLaunchSupport[];
  closingNote: string;
}

export interface Partner {
  name: string;
  category: string;
}

export interface FinderOption {
  label: string;
  stage: StageId;
}

export interface FinderQuestion {
  id: string;
  prompt: string;
  options: FinderOption[];
}

/** A simple titled step (used by the founder steps, flywheel, and recognition). */
export interface TextStep {
  title: string;
  body: string;
}

export interface Founder {
  eyebrow: string;
  title: string;
  intro: string;
  finderTitle: string;
  finderSubtitle: string;
  finderResultTitle: string;
  finderRestart: string;
  finderRecommended: string;
  pipelineTitle: string;
  pipelineSubtitle: string;
  stepsTitle: string;
  steps: TextStep[];
  finderCalloutTitle: string;
  finderCalloutBody: string;
  finderCalloutCta: string;
  finderReasonLabel: string;
  headerImage?: string;
  headerImageAlt?: string;
}

export interface InvolvementWay {
  icon: string;
  title: string;
  body: string;
}

export interface Advisor {
  eyebrow: string;
  title: string;
  intro: string;
  flywheelTitle: string;
  flywheelSteps: TextStep[];
  waysTitle: string;
  ways: InvolvementWay[];
  peoTitle: string;
  peoBody: string;
  goalsTitle: string;
  goalsSubtitle: string;
  goals: Stat[];
  recognitionTitle: string;
  recognition: TextStep[];
  mentorsTitle: string;
  mentorsSubtitle: string;
  mentorsNote: string;
  ctaTitle: string;
  ctaBody: string;
  ctaButton: string;
  headerImage?: string;
  headerImageAlt?: string;
}

export interface Mentor {
  name: string;
  role: string;
  field: string;
  bio: string;
  expertise: string[];
  quote: string;
  /** If set, this person is featured in the homepage "ventures built here" strip. */
  venture?: string;
}

export interface MentorsPage {
  eyebrow: string;
  title: string;
  subtitle: string;
  filterLabel: string;
  filterAll: string;
  countLabel: string;
  emptyLabel: string;
}

export interface Footer {
  blurb: string;
  rights: string;
  contact: string;
}

export interface TeamMember {
  name: string;
  role: string;
}

export interface LaunchPost {
  id: string;
  /** Venture name / headline. */
  title: string;
  /** What they are building. */
  vision: string;
  /** Current team members. */
  team: TeamMember[];
  /** Cofounder skills sought (drives the filter and the tags). */
  seeking: string[];
  /** Contact email; falls back to LaunchpadCopy.fallbackContact. */
  contact?: string;
  /** Runtime-only: true for posts a visitor created in their browser. Never in YAML. */
  local?: boolean;
}

export interface StudentProfile {
  id: string;
  name: string;
  /** Program / credential, e.g. "Software Engineering". */
  degree: string;
  /** Optional specialization. */
  concentration?: string;
  /** Year of study, e.g. "3rd year". */
  year: string;
  /** Areas of interest (drives the filter and the tags). */
  interests: string[];
  /** What the student is looking for. */
  looking: string;
  /** Contact email; falls back to StudentCopy.fallbackContact. */
  contact?: string;
  /** Runtime-only: true for profiles a visitor created in their browser. */
  local?: boolean;
}

export interface StudentCopy {
  countLabel: string;
  filterLabel: string;
  filterAll: string;
  emptyLabel: string;
  note: string;
  postButton: string;
  postCancel: string;
  formTitle: string;
  formIntro: string;
  nameLabel: string;
  namePlaceholder: string;
  degreeLabel: string;
  degreePlaceholder: string;
  concentrationLabel: string;
  concentrationPlaceholder: string;
  yearLabel: string;
  yearPlaceholder: string;
  interestsLabel: string;
  interestsHint: string;
  interestsPlaceholder: string;
  lookingLabel: string;
  lookingPlaceholder: string;
  contactLabel: string;
  contactPlaceholder: string;
  submitButton: string;
  formError: string;
  interestsHeading: string;
  lookingHeading: string;
  reachOut: string;
  yourPostBadge: string;
  removeLabel: string;
  fallbackContact: string;
  mailtoSubject: string;
}

export interface LaunchpadCopy {
  eyebrow: string;
  title: string;
  subtitle: string;
  countLabel: string;
  filterLabel: string;
  filterAll: string;
  emptyLabel: string;
  note: string;
  // Post toggle + form
  postButton: string;
  postCancel: string;
  formTitle: string;
  formIntro: string;
  titleLabel: string;
  titlePlaceholder: string;
  visionLabel: string;
  visionPlaceholder: string;
  teamLabel: string;
  teamHint: string;
  teamPlaceholder: string;
  seekingLabel: string;
  seekingHint: string;
  seekingPlaceholder: string;
  contactLabel: string;
  contactPlaceholder: string;
  submitButton: string;
  formError: string;
  // Card
  teamHeading: string;
  seekingHeading: string;
  reachOut: string;
  yourPostBadge: string;
  removeLabel: string;
  fallbackContact: string;
  mailtoSubject: string;
  // Founder-page callout
  calloutTitle: string;
  calloutBody: string;
  calloutCta: string;
  // Two-sided board
  tabVentures: string;
  tabStudents: string;
  students: StudentCopy;
}

// ---------------------------------------------------------------------------
// Parsed content
// ---------------------------------------------------------------------------

const home = frontmatter(homeRaw);
export const brand = home.brand as Brand;
export const landing = home.landing as Landing;
export const heroStats = home.heroStats as Stat[];
export const photoBand = (home.photoBand ?? []) as PhotoBandItem[];
export const principles = home.principles as Principle[];
export const roleCards = home.roleCards as RoleCard[];
export const footer = home.footer as Footer;
export const venturesStrip = home.venturesStrip as VenturesStrip;

export const stages = frontmatter(pipelineRaw).stages as Stage[];
export const umbrella = frontmatter(pipelineRaw).umbrella as Umbrella;
export const exploreTracks = frontmatter(pipelineRaw).exploreTracks as ExploreTrack[];
export const programs = frontmatter(programsRaw).programs as Program[];
export const productStudio = frontmatter(productStudioRaw)
  .productStudio as ProductStudio;
export const makerLaunch = frontmatter(makerLaunchRaw)
  .makerLaunch as MakerLaunch;

const founderFm = frontmatter(founderRaw);
export const founder = founderFm.founder as Founder;
export const finderQuestions = founderFm.finderQuestions as FinderQuestion[];

const advisorFm = frontmatter(advisorRaw);
export const advisor = advisorFm.advisor as Advisor;
export const partners = advisorFm.partners as Partner[];
export const mentorsPage = advisorFm.mentorsPage as MentorsPage;

export const mentors = frontmatter(mentorsRaw).mentors as Mentor[];

const launchpadFm = frontmatter(launchpadRaw);
export const launchpadPage = launchpadFm.launchpadPage as LaunchpadCopy;
export const launchpadPosts = launchpadFm.launchpadPosts as LaunchPost[];
export const launchpadProfiles = launchpadFm.launchpadProfiles as StudentProfile[];
